POST http://localhost:3300/contacts
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "User",
    "email": "test@gmail.com",
    "favoriteColor": "yellow",
    "birthday": "2000-01-01"
}

###

PUT http://localhost:3300/contacts/68c06e60f54133bb1160d4a7
Content-Type: application/json

{
    "firstName": "Updated",
    "lastName": "User",
    "email": "updated@gmail.com",
    "favoriteColor": "purple",
    "birthday": "1999-12-31"
}

###

DELETE http://localhost:3300/contacts/68c06e66f54133bb1160d4a8