POST http://localhost:3300/contacts
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "User",
    "email": "test@gmail.com",
    "favoriteColor": "yellow",
    "birthday": "2000-01-01"
}

# Should create a new contact and return the new contact's ID

###

PUT http://localhost:3300/contacts/68c07a0e9e4588ae559da814
Content-Type: application/json

{
    "firstName": "Updated",
    "lastName": "User",
    "email": "updated@gmail.com",
    "favoriteColor": "purple",
    "birthday": "1999-12-31"
}

# Should update the contact with the specified ID
# Replace the ID with an actual contact ID to test

###

DELETE http://localhost:3300/contacts/68c07a0e9e4588ae559da814
# Should delete the contact with the specified ID
# Replace the ID with an actual contact ID to test